# Generated by Django 4.1.4 on 2022-12-12 21:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='livros',
            fields=[
                ('id_livro', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=500)),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
