# Generated by Django 4.1.4 on 2022-12-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='data',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='descricao',
        ),
        migrations.AddField(
            model_name='livros',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='livros',
            name='genero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='livros',
            name='sinopse',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='livros',
            name='autor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='livros',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
