# Generated by Django 4.1.4 on 2022-12-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0002_remove_livros_data_remove_livros_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='id_livro',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
