# Generated by Django 4.1.4 on 2022-12-27 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0004_alter_livros_id_livro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livros',
            old_name='id_livro',
            new_name='id',
        ),
    ]
